[project]
name = "ghm"
authors = [{name = "Kamil Turek", email = "kamil.turek@hotmail.com"}]
version = "0.1.0"
requires-python = ">=3.7"
dependencies = [
    "click==8.1.3",
]

[project.optional-dependencies]
dev = [
    "pytest==7.3.1",
]

[tool.setuptools]
packages = ["ghm"]
